name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 🔍 TEMPORARY DEBUG STEP for Secrets
    - name: 🔍 Debug Docker Secrets
      run: |
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "❌ DOCKER_PASSWORD is missing or blank"
          exit 1
        else
          echo "✅ DOCKER_PASSWORD is present"
        fi

    - name: Build sender image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sender:latest ./sender

    - name: Build receiver image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/receiver:latest ./receiver

    - name: Push sender image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/sender:latest

    - name: Push receiver image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/receiver:latest
#
#